The return of Maxim's service account key generation

diff --git a/core/controlplane/config/templates/cloud-config-controller b/core/controlplane/config/templates/cloud-config-controller
--- a/core/controlplane/config/templates/cloud-config-controller
+++ b/core/controlplane/config/templates/cloud-config-controller
@@ -44,6 +44,60 @@ coreos:
     etcd_keyfile: /etc/kubernetes/ssl/etcd-client-key.pem
   {{- end }}
   units:
+{{/* RUN-509 Remove vault-based certs */}}
+    - name: refresh-sa-secret.service
+      enable: true
+      command: start
+      content: |
+        [Unit]
+        Description=Generates and updates ServiceAccount keys
+        After=bootstrap-serviceaccount-key.service kubelet.service network-online.target
+        Wants=kubelet.service
+
+        [Service]
+        Type=simple
+        Restart=on-failure
+        RestartSec=30
+        # keys expire every 30 days
+        Environment=KEY_EXPIRE_PERIOD_SEC=2592000
+        # attempt to renew keys 5 days before expire time
+        Environment=KEY_RENEW_THRESHOLD_SEC=432000
+        ExecStartPre=/usr/bin/systemctl is-active kubelet
+        ExecStartPre=/opt/bin/refresh-sa-secret /etc/kubernetes/ssl/serviceaccount-key.pem
+        ExecStart=/bin/true
+
+        [Install]
+        WantedBy=multi-user.target
+
+    - name: refresh-sa-secret.timer
+      enable: true
+      command: start
+      content: |
+        [Timer]
+        OnUnitInactiveSec=10m
+
+    - name: bootstrap-serviceaccount-key.service
+      enable: true
+      command: start
+      content: |
+        [Unit]
+        # This key is actually never used to create ServiceAccount secret, because
+        # SA secret creation is done in controller-manager which will be failing to start
+        # until serviceaccount-key.pem.controller is created by 'refresh-sa-secret.service'
+        # So whole purpose of this file is to allow APIserver to start and let `refresh-sa-secret.service`
+        # to do it's job
+        Description=Creates initial SA key to allow apiserver to start on first boot
+        Before=kubelet.service
+        Requires=network-online.target
+
+        [Service]
+        Type=oneshot
+        ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/ssl
+        ExecStart=/bin/sh -ec '[ -f /etc/kubernetes/ssl/serviceaccount-key.pem.apiserver ] || openssl ecparam -name prime256v1 -genkey -out /etc/kubernetes/ssl/serviceaccount-key.pem.apiserver'
+        [Install]
+        WantedBy=kubelet.service
+
+{{/* RUN-509 Remove vault-based certs */}}
 {{- range $u := .Controller.CustomSystemdUnits}}
     - name: {{$u.Name}}
       {{- if $u.Command }}
@@ -565,6 +619,177 @@ write_files:
       PrintMotd no # handled by PAM
       PasswordAuthentication no
       ChallengeResponseAuthentication no
+
+{{/* RUN-509 Remove vault-based certs */}}
+  - path: /opt/bin/refresh-sa-secret
+    permissions: 0755
+    content: |
+      #!/bin/bash
+      set -ue
+
+      # Script tries to coordinate secret update/creation among multiple independend nodes. Only coordination
+      # primitive it is using is `kubectl create` which is assumed to be atomic and race-free (==
+      # if simultaneous `kubectl create` commands issued, only one can possibly return success)
+
+      # Script need to be careful to maintain following MUST HAVE properties:
+      #  1. Every cert written to secrets must stay there and never overwriten by a new one.
+      #     So if we have 2 active certs [A,B], there can never be update [A,B,C], followed up
+      #     with [A,B,C']. If that happens, "C" cert, no matter how little time it
+      #     stayed in secrets, can possibly be used to generate service account tokens, therefore
+      #     overwriting it with "C'" would break all pods which were started
+      #
+
+      : ${LOCK_EXPIRE_TIMEOUT_SECONDS:=20}  # maximum time any operation under lock can take
+      : ${KEY_EXPIRE_PERIOD_SEC:=$(( 60*60*24*365*2 ))} # 2 years
+      : ${KEY_RENEW_THRESHOLD_SEC:=$(( $KEY_EXPIRE_PERIOD_SEC - 30 ))}  # time left before expire, when to attempt key renew
+      KEY_EXPIRE_THRESHOLD_SECONDS=$(( KEY_EXPIRE_PERIOD_SEC - KEY_RENEW_THRESHOLD_SEC ))
+      UPDATE_OPERATION_TIMEOUT=$(( LOCK_EXPIRE_TIMEOUT_SECONDS / 2 ))
+
+      P=serviceaccount-keys
+
+      # produces secret resource definition. .
+      # second argument is optional and goes into 'data' field and must be a string value
+      secret() {
+        local name=$1
+        if (( $# > 1 )); then
+            local T=$(mktemp /tmp/sakey/tmp.XXXXXXX)
+            echo "$2" >$T
+            kubectl --namespace=kube-system create secret generic "${name}" --from-file="keypairs=$T" --dry-run -o json
+            rm $T
+        else
+            kubectl --namespace=kube-system create secret generic "${name}" --dry-run -o json
+        fi
+      }
+
+      kubectl() {
+        docker run --rm -i --net=host -v /tmp/sakey:/tmp/sakey -v /etc/kubernetes:/etc/kubernetes:ro -v /etc/resolv.conf:/etc/resolv.conf:ro {{.HyperkubeImage.RepoWithTag}} /kubectl "$@"
+      }
+
+      log() {
+        >&2 echo "$@"
+      }
+
+      gen_new_key() {
+        openssl ecparam -name prime256v1 -genkey -noout
+      }
+
+      get_key() {
+        local name=$1
+        kubectl --namespace=kube-system get -o json secret "${name}"
+      }
+
+      init_key() {
+        local name=$1
+        secret "${name}" '[]' | kubectl --namespace=kube-system create -f -
+      }
+
+      # caller MUST guarantee that it has right to update this key == no other servers will try to update it
+      update_secret() {
+          local name=$1
+          local data=$2
+          local new_keypairs new_secret
+
+          local new_keypairs keypairs_b64
+          new_keypairs=$(get_key "${name}" \
+            | jq -er '.data.keypairs' \
+            | base64 -d \
+            | jq --arg new_key "${data}" -er \
+              '([ {key: $new_key, createdAt: now} ] + .) | tojson')
+          new_secret=$(secret "${name}" "${new_keypairs}")
+          have_good_secret "${new_secret}" || {
+              log "** ERROR/BUG: We generated a key, but didn't produce result which passes 'have_good_secret' check. K8S secret will not be updated"
+              return 1
+          }
+          kubectl --namespace=kube-system --request-timeout="${UPDATE_OPERATION_TIMEOUT}s" replace -f - <<<"${new_secret}"
+      }
+
+      # expects a single arg `secret_json`, which is a content of secret in k8s
+      # it examines certs stored in it and identifies if it is a good one to be used, or
+      # we need a better one
+      have_good_secret() {
+          local secret=$1
+          log "Check that first key doesn't expire within threshold=${KEY_EXPIRE_THRESHOLD_SECONDS} seconds"
+          [[ -n "${secret}" ]] || return $?
+          jq -er '.data.keypairs' <<<"${secret}" | base64 -d | jq --arg expire_threshold ${KEY_EXPIRE_THRESHOLD_SECONDS} -e \
+            '.[0].createdAt as $createdAt
+            | $createdAt != null
+              and now - $createdAt < ($expire_threshold|tonumber)'
+      }
+
+      release_lock() {
+        local name=$1
+        kubectl --namespace=kube-system delete secret/"${name}"
+      }
+
+      # "Lock" here is an atomically created sa-key-lock secret
+      acquire_lock() {
+          local name=$1
+          log "acquire_lock ${name}"
+          secret "${name}" | kubectl --namespace=kube-system create -f - || {
+              log -n "acquire_lock failed, checking if lock is stale"
+              get_key "${name}" | jq -e "now - (.metadata.creationTimestamp|fromdate) < $LOCK_EXPIRE_TIMEOUT_SECONDS" >/dev/null || {
+                  log "${name} is a stale lock, deleting it so it can be reacquired"
+                  release_lock ${name} || log "Lock deletion failed, but we ignore this error as it is racey"
+              }
+              return 1  # need to return error, to indicate we failed to aquire lock, so that caller can try again
+          }
+      }
+
+      update_key() {
+        local key=$1
+        local new_secret=$2
+        local filter=$3
+        local updated="false"
+
+        local new_keys=$(jq -er '.data.keypairs' <<<"${new_secret}" | base64 -d | jq -er '.[].key') || :
+
+        if [[ ! -f "${key}" ]]; then
+          log "creating missing file ${key}"
+          echo "${new_keys}" >$key
+          updated="true"
+        else
+          if [[ "$(cat ${key})" != "${new_keys}" ]]; then
+            log "${key} is out of date, updating..."
+            echo "${new_keys}" >$key
+            updated="true"
+          else
+            log "ok - ${key} matches - ok, nothing to do"
+          fi
+        fi
+
+        if [[ "${updated}" == "true" ]]; then
+          log "killing docker container matching ${filter}"
+          docker ps --filter name=$filter -q | xargs --no-run-if-empty docker rm -f
+        fi
+      }
+
+      # MAIN
+
+      init_key "$P" &>/dev/null || :  # ignore errors if key can't be created if it was by someone else
+      SECRET_JSON=$(get_key "$P") || :
+
+      while ! have_good_secret "$SECRET_JSON"; do
+        log "Secret not good: ${SECRET_JSON}"
+        : ${new_key_json:=$(gen_new_key)}
+        if acquire_lock "${P}-lock"; then
+          echo "Successfully aquired lock, updating secret."
+          update_secret "$P" "$new_key_json" || { release_lock "${P}-lock"; exit 1; } # populate_key_with_data is guaranteed to complete in < LOCK_EXPIRE time
+          release_lock "${P}-lock"
+          SECRET_JSON=$(get_key "$P") || :
+          break
+        else
+          log "Error or somebody else acquired lock, waiting sleeping for 10 seconds"
+          sleep 10
+        fi
+        SECRET_JSON=$(get_key "$P") || :
+      done
+
+      # Once we have run it is ok for apiservers to bind to 0.0.0.0
+      sed -e 's/bind-address=127.0.0.1/bind-address=0.0.0.0/g' -i /etc/kubernetes/manifests/kube-apiserver.yaml
+      update_key "$1.apiserver" "${SECRET_JSON}" "k8s_kube-apiserver*"
+      update_key "$1.controller" "${SECRET_JSON}" "k8s_kube-controller-manager*"
+
+{{/* RUN-509 Remove vault-based certs */}}
 
 {{- if .Controller.CustomFiles}}
   {{- range $w := .Controller.CustomFiles}}
@@ -3423,7 +3648,9 @@ write_files:
           - /hyperkube
           - apiserver
           - --apiserver-count={{if .MinControllerCount}}{{ .MinControllerCount }}{{else}}{{ .ControllerCount }}{{end}}
-          - --bind-address=0.0.0.0
+{{/* RUN-509 Remove vault-based certs - this should be 0.0.0.0 once service account signing keys are fixed */}}
+          - --bind-address=127.0.0.1
+{{/* RUN-509 Remove vault-based certs */}}
           - --etcd-servers=#ETCD_ENDPOINTS#
           - --etcd-cafile=/etc/kubernetes/ssl/etcd-trusted-ca.pem
           - --etcd-certfile=/etc/kubernetes/ssl/etcd-client.pem
@@ -3477,7 +3704,9 @@ write_files:
           - --tls-cert-file=/etc/kubernetes/ssl/apiserver.pem
           - --tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
           - --client-ca-file=/etc/kubernetes/ssl/ca.pem
-          - --service-account-key-file=/etc/kubernetes/ssl/service-account-key.pem
+{{/* RUN-509 Remove vault-based certs DO NOT TOUCH THIS LINE */}}
+          - --service-account-key-file=/etc/kubernetes/ssl/serviceaccount-key.pem.apiserver
+{{/* RUN-509 Remove vault-based certs DO NOT TOUCH THIS LINE */}}
           - --runtime-config=extensions/v1beta1/networkpolicies=true,batch/v2alpha1=true{{if .Experimental.Admission.PodSecurityPolicy.Enabled}},extensions/v1beta1/podsecuritypolicy=true{{ end }}{{if .Experimental.Admission.Initializers.Enabled}},admissionregistration.k8s.io/v1alpha1{{end}}{{if .Experimental.Admission.Priority.Enabled}},scheduling.k8s.io/v1alpha1=true{{end}}
          {{if .Experimental.Admission.Priority.Enabled}}
           - --feature-gates=PodPriority=true
@@ -3590,7 +3819,9 @@ write_files:
 {{/* RUN Enable verbose logging */}}
           - --master=http://127.0.0.1:8080
           - --leader-elect=true
-          - --service-account-private-key-file=/etc/kubernetes/ssl/service-account-key.pem
+{{/* RUN-509 Remove vault-based certs DO NOT TOUCH THIS LINE */}}
+          - --service-account-private-key-file=/etc/kubernetes/ssl/serviceaccount-key.pem.controller
+{{/* RUN-509 Remove vault-based certs DO NOT TOUCH THIS LINE */}}
           {{ if .Experimental.TLSBootstrap.Enabled }}
           - --insecure-experimental-approve-all-kubelet-csrs-for-group=system:kubelet-bootstrap
           - --cluster-signing-cert-file=/etc/kubernetes/ssl/worker-ca.pem
@@ -5214,6 +5445,48 @@ write_files:
           omitStages:
             - "RequestReceived"
 {{ end -}}
+
+{{/* RUN-509 Remove vault-based certs */}}
+  - path: /opt/bin/check-pod-serviceaccount-secrets
+    permissions: 0755
+    content: |
+      #!/bin/bash
+
+      KUBEPATH=/etc/kubernetes/serviceaccount-secret/
+      mkdir -p ${KUBEPATH}
+
+      # Get the current serviceaccount secret
+      SECRET=$( /kubectl get serviceaccount default --namespace=kube-system --output=json | jq -e --raw-output '.secrets[0].name' )
+      echo $SECRET > ${KUBEPATH}secret-name
+
+      # Produce a list of pods that reference any serviceaccount secret other than the current serviceaccount secret
+      /kubectl get pods --namespace=kube-system --output=json | jq --arg good_tokens "$SECRET" '[ .items[]
+        | { podName: .metadata.name, serviceAccountTokens: [.spec.containers[].volumeMounts[]?]
+        | [map(select(.mountPath == "/var/run/secrets/kubernetes.io/serviceaccount"))[].name] | unique } ]
+        | map(select((.serviceAccountTokens - [$good_tokens]) | length > 0)) '
+
+
+  - path: /opt/bin/rotate-serviceaccount-secret
+    permissions: 0755
+    content: |
+      #!/bin/bash
+
+      KUBEPATH=/etc/kubernetes/serviceaccount-secret/
+      SECRET_ID=$(cat ${KUBEPATH}secret-name)
+
+      # Get latest secret id
+      /opt/bin/check-pod-serviceaccount-secrets
+
+      # Remove secret (new one is regenerated)
+      /kubectl delete secret ${SECRET_ID} --namespace=kube-system
+
+      # Trigger rolling-updates
+      /kubectl patch --namespace kube-system deployment kube-dns -p   "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
+      /kubectl patch --namespace kube-system deployment calico-policy-controller -p   "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
+      /kubectl patch --namespace kube-system deployment heapster-v1.2.0 -p   "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
+      /kubectl patch --namespace kube-system deployment kube-dns-autoscaler -p   "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
+      /kubectl replace --namespace kube-system daemonset calico-node -p   "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
+{{/* RUN-509 Remove vault-based certs */}}
 
 {{if .Experimental.Authentication.Webhook.Enabled}}
   - path: /etc/kubernetes/webhooks/authentication.yaml
